# Generated by Django 5.0.1 on 2024-01-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=15)),
                ("capacidade_leitos", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("genero", models.CharField(max_length=10)),
                ("endereco", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=15)),
                ("historico_medico", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateField()),
                ("sintomas", models.TextField()),
                ("diagnostico", models.TextField()),
                ("tratamento", models.TextField()),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saudepublica.hospital",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saudepublica.paciente",
                    ),
                ),
            ],
        ),
    ]
