# Generated by Django 5.0.1 on 2024-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saudepublica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
